### PR TITLE
fix: GetGlyph falls back to index 0 when rune is not found

### LINKED ISSUE #58: tinyfont.WriteLine renders wrong glyphs for missing codepoints
When trying to render characters that are not included in the font, instead of skipping or showing a placeholder (e.g. □), the renderer draws an **incorrect glyph from a different character**.
In this case, for `"①②③④⑤"`, only ①–③ are included in the font. However, ④ (U+2463) and ⑤ (U+2464) incorrectly display as **"字" (U+5B57)**.
## Environment
* TinyGo × TinyFont × WebAssembly (browser rendering)
* Example font snippet (only ①–③ are registered):

```
"\x00\x24\x60" + "\x00\x10\x3F" + // ① U+2460
"\x00\x24\x61" + "\x00\x10\x6F" + // ② U+2461
"\x00\x24\x62" + "\x00\x10\x9F" + // ③ U+2462
"\x00\x5B\x57" + "\x00\x10\xCF" + // 字 U+5B57

```

## Steps to Reproduce
1. Prepare a font with only ①②③ and "字" registered.
2. Run:

```
tinyfont.WriteLine(target, &testfont, 10, 50, "①②③④⑤", color.RGBA{0, 0, 0, 255})

```
3. Observe the output.

Image

## Expected Behavior
* Unregistered characters (④⑤) should not be drawn, or should render as a placeholder (e.g., □ or ?).
* At minimum, they should **not render as a completely unrelated glyph**.
## Actual Behavior
* Output shows: `①②③字字`
* Unregistered ④⑤ are replaced with the glyph for "字".
## Impact
* Any unregistered character may render as a **wrong but valid glyph**.
* This can lead to confusing or misleading text output, especially in UI or educational use cases where accuracy of glyphs is critical.
* The issue is not limited to circled numbers; any missing codepoint can incorrectly map to the glyph of a different registered character.

### PR DESCRIPTION
**Pull request by rdon-key**
This pull request fixes an issue where `GetGlyph` could return the glyph of the next larger rune if the requested rune was not found in the font.  
As a result, undefined characters could be rendered as completely unrelated glyphs (see #58).

### Changes
- Updated `GetGlyph` in both `const1bit` and `const2bit` packages:
  - Added an equality check (`==`) during the binary search.
  - Introduced a `found` flag to ensure that if no match is found, the function always falls back to index 0.
- Updated function comments to explicitly state that undefined runes return the glyph at index 0.

### Verification
- Verified with `const2bit` fonts (WebAssembly rendering).  
- Could not test with `const1bit` fonts locally, but the implementation is identical.

```
tinyfont.WriteLine(target, &testfont, 10, 50, "①②③④⑤", color.RGBA{0, 0, 0, 255})
```

image

### Impact
- Undefined runes will no longer render as unrelated valid glyphs.  
- Instead, they consistently fall back to glyph 0 (commonly a space or placeholder).

Fixes #58

### CODE REVIEW

File: const1bit/const1bit.go [hunk 1]
```diff
@@ -77,28 +77,34 @@ func (f *Font) GetYAdvance() uint8 {
...
 		}
 	}
 
-	if s > len(font.OffsetMap)/6-1 {
+	if !found {
 		s = 0
 	}
 
 	offset := uint32(font.OffsetMap[s*6+3])<<16 + uint32(font.OffsetMap[s*6+4])<<8 + uint32(font.OffsetMap[s*6+5])
+
```
Comment (sago35) [inline const1bit/const1bit.go]: Please revert the parts unrelated to the changes in this PR.
Of course, fixing them in a separate PR is totally fine.

File: const1bit/const1bit.go [hunk 2]
```diff
@@ -111,5 +117,5 @@ func (font *Font) GetGlyph(r rune) tinyfont.Glypher {
 	font.glyph.XOffset = int8(font.Data[offset+3])
 	font.glyph.YOffset = int8(font.Data[offset+4])
 	font.glyph.Bitmaps = []byte(font.Data[offset+5 : offset+5+sz])
-	return &(font.glyph)
+	return &font.glyph
```
Comment (sago35) [inline const1bit/const1bit.go]: Same as above.

File: const2bit/const2bit.go [hunk 3]
```diff
@@ -83,28 +83,34 @@ func (f *Font) GetYAdvance() uint8 {
...
 		}
 	}
 
-	if s > len(font.OffsetMap)/6-1 {
+	if !found {
 		s = 0
 	}
 
 	offset := uint32(font.OffsetMap[s*6+3])<<16 + uint32(font.OffsetMap[s*6+4])<<8 + uint32(font.OffsetMap[s*6+5])
+
```
Comment (sago35) [inline const2bit/const2bit.go]: Same as above.

File: const2bit/const2bit.go [hunk 4]
```diff
@@ -117,5 +123,5 @@ func (font *Font) GetGlyph(r rune) tinyfont.Glypher {
 	font.glyph.XOffset = int8(font.Data[offset+3])
 	font.glyph.YOffset = int8(font.Data[offset+4])
 	font.glyph.Bitmaps = []byte(font.Data[offset+5 : offset+5+sz])
-	return &(font.glyph)
+	return &font.glyph
```
Comment (sago35) [inline const2bit/const2bit.go]: Same as above.

**Review by sago35 — CHANGES_REQUESTED** [review]
Thank you. The content of the PR is excellent. I’d just like to request a few minor changes. @rdon-key

**Comment by rdon-key** [comment]
All unrelated changes have been reverted.  
This PR now only includes the fallback fix for undefined runes.  
Thanks for your review!

**Review by sago35 — APPROVED** [review]
LGTM

Thanks for your contribution.
Now merging.
